DROP DATABASE IF EXISTS DB_TCCGRUPO1;
CREATE DATABASE DB_TCCGRUPO1;

USE DB_TCCGRUPO1;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
	, SEXO CHAR(1)
	, DT_NASCIMENTO DATE
) ENGINE INNODB;

CREATE TABLE AMIGO (
	IDAMIGO INT NOT NULL
	, IDUSUARIO INT NOT NULL
	, SITUACAO ENUM('PENDENTE', 'CONFIRMADO', 'NEGADO')
	, CONSTRAINT PK_AMIGO PRIMARY KEY (IDAMIGO, IDUSUARIO)
	, CONSTRAINT FK_AMIGO_AMIGO FOREIGN KEY(IDAMIGO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_AMIGO_USUARIO FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE INNODB;

CREATE TABLE CATEGORIA (
	IDCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, DESCRICAO TEXT
) ENGINE INNODB;

CREATE TABLE LOCALIDADE (
	IDLOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDCATEGORIA INT NOT NULL
	, IDUSUARIO INT
	, NOME VARCHAR(100)
	, DESCRICAO TEXT
	, DT_LOCALIDADE DATETIME DEFAULT NOW()
	, CONSTRAINT FK_LOCALIDADE_CATEGORIA FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_LOCALIDADE_USUARIO FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;


CREATE TABLE PONTO (
	IDPONTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDLOCALIDADE INT NOT NULL
	, IDUSUARIO INT
	, DESCRICAO TEXT
	, LATITUDE NUMERIC(12,7)
	, LONGITUDE NUMERIC(12,7)
	, ALTITUDE NUMERIC(12,7)
	, DT_PONTO DATETIME DEFAULT NOW()
	, CONSTRAINT FK_PONTO_LOCALIDADE FOREIGN KEY (IDLOCALIDADE) REFERENCES LOCALIDADE(IDLOCALIDADE) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_PONTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;


CREATE TABLE FOTO (
	IDFOTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDLOCALIDADE INT NOT NULL
	, IDUSUARIO INT 
	, DESCRICAO TEXT
	, CONSTRAINT FK_FOTO_LOCALIDADE FOREIGN KEY (IDLOCALIDADE) REFERENCES LOCALIDADE(IDLOCALIDADE) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_FOTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;


CREATE TABLE COMENTARIO_FOTO (
	IDCOMENTARIO_FOTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDFOTO INT NOT NULL
	, IDUSUARIO INT
	, TEXTO TEXT
	, DT_COMENTARIO DATETIME DEFAULT NOW()
	, CONSTRAINT FK_COMENTARIO_FOTO_FOTO FOREIGN KEY (IDFOTO) REFERENCES FOTO(IDFOTO) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_COMENTARIO_FOTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;

CREATE TABLE COMENTAR_LOCALIDADE (
	IDCOMENTARIO_LOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDLOCALIDADE INT NOT NULL
	, IDUSUARIO INT
	, TEXTO TEXT
	, DT_COMENTARIO DATETIME DEFAULT NOW()
	, CONSTRAINT FK_COMENTARIO_LOCALIDADE_LOCALIDADE FOREIGN KEY (IDLOCALIDADE) REFERENCES LOCALIDADE(IDLOCALIDADE) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_COMENTARIO_LOCALIDADE_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;

CREATE TABLE CURTIR_FOTO (
	IDFOTO INT NOT NULL
	, IDUSUARIO INT NOT NULL
	, DT_CURTIR DATETIME DEFAULT NOW()
	, CONSTRAINT PK_CURTIR_FOTO PRIMARY KEY (IDFOTO, IDUSUARIO)
	, CONSTRAINT FK_CURTIR_FOTO_FOTO FOREIGN KEY (IDFOTO) REFERENCES FOTO(IDFOTO) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_CURTIR_FOTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE INNODB;

CREATE TABLE CURTIR_LOCALIDADE (
	IDLOCALIDADE INT NOT NULL
	, IDUSUARIO INT NOT NULL
	, DT_CURTIR DATETIME DEFAULT NOW()
	, CONSTRAINT PK_CURTIR_LOCALIDADE PRIMARY KEY (IDLOCALIDADE, IDUSUARIO)
	, CONSTRAINT FK_CURTIR_LOCALIDADE_LOCALIDADE FOREIGN KEY (IDLOCALIDADE) REFERENCES LOCALIDADE(IDLOCALIDADE) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_CURTIR_LOCALIDADE_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE INNODB;

